/***********************************************************************/
/*                                                                     */
/*  FILE        :bert100.c                                             */
/*  DATE        :Tue, Apr 02, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX63N                                                 */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
                    

#include "iodefine.h"
#include "types.h"
#include "timer.h"
#include "events.h"
#include "threads.h"
#include "console.h"
#include "sci0.h"
#include "interpreter.h"
#include "hex.h"
#include "editor.h"
#include "threads.h"
#include "tpos.h"

/* Configure the clock to 96MHz CPU / 48MHz Peripheral */
void
ConfigureClocks(void)
{
	uint32_t i;
	SYSTEM.MOSCWTCR.BYTE = 0x0d;
	SYSTEM.PLLWTCR.BYTE = 0xE;
	SYSTEM.PLLCR.WORD = 0x0f00;
	SYSTEM.MOSCCR.BYTE = 0x00;
	SYSTEM.PLLCR2.BIT.PLLEN = 0; 
	for(i = 0; i < 3000;i++) {
		asm("nop":::"memory");	
	}
	SYSTEM.SCKCR.LONG = 0x21821211;
	SYSTEM.SCKCR2.WORD = 0x033;
	SYSTEM.SCKCR3.WORD = 0x400;
}


int main()
{

	Interp *interp;
        Editor *editor;
	/* Disable register protection permanently */
	SYSTEM.PRCR.WORD = 0xa50b;
	/* Disable Pin function write protections permanently */	
	MPC.PWPR.BYTE = 0x00;
	MPC.PWPR.BYTE = 0x40;
	/*
 	*/
 	BSET(6,PORT1.PDR.BYTE);
 	BSET(6,PORT1.PODR.BYTE);

	ConfigureClocks();
	Threads_Init();
	TPOS_Init();
	Timers_Init();
	Sci0_Init(115200);
	interp = Interp_Init(Con_OutStr, Con_PrintVA);
	editor = Editor_Init(Interp_Feed, interp);
	Con_RegisterSink(Editor_Feed, editor);


	//ENABLE_IRQ();
	EV_Loop();
}
	
